Config.Vehicles = {
	{
		name = 'BF Club',
		brand = 'BF',
		model = 'Club',
		price = 15000,
		category = 'compacts',
        categoryLabel = 'Compacts',
		hashname = 'club',
		hash = `club`,
		shop = 'normal',
	},
	{
		name = 'Blista Kanjo',
		brand = 'Blista',
		model = 'Kanjo',
		price = 32300,
		category = 'compacts',
        categoryLabel = 'Compacts',
		hashname = 'kanjo',
		hash = `kanjo`,
		shop = 'normal',
	},
    {
		name = 'Benefactor Panto',
		brand = 'Benefactor',
		model = 'Panto',
		price = 18500,
		category = 'compacts',
        categoryLabel = 'Compacts',
		hashname = 'panto',
		hash = `panto`,
		shop = 'normal',
    },
	
	-- Muscle
	{
		name = 'Vapid Dominator Sport',
		brand = 'Vapid',
		model = 'Dominator Sport',
		price = 50000,
		category = 'muscle',
        categoryLabel = 'Muscle',
		hashname = 'dominator3',
		hash = `dominator3`,
		shop = 'normal',
	},
	{
		name = 'Vapid Challenger Sport',
		brand = 'Vapid',
		model = 'Challenger Sport',
		price = 50000,
		category = 'muscle',
        categoryLabel = 'Muscle',
		hashname = 'dominator7',
		hash = `dominator7`,
		shop = 'normal',
	},
	{
		name = 'Albany Buccaneer',
		brand = 'Albany',
		model = 'Buccaneer',
		price = 50000,
		category = 'muscle',
        categoryLabel = 'Muscle',
		hashname = 'buccaneer2',
		hash = `buccaneer2`,
		shop = 'normal',
	},
	{
		name = 'Vapid Chino',
		brand = 'Vapid',
		model = 'Chino',
		price = 50000,
		category = 'muscle',
        categoryLabel = 'Muscle',
		hashname = 'chino2',
		hash = `chino2`,
		shop = 'normal',
	},
	{
		name = 'Declasse Tampa',
		brand = 'Declasse',
		model = 'Tampa',
		price = 171000,
		category = 'muscle',
        categoryLabel = 'Muscle',
		hashname = 'tampa',
		hash = `tampa`,
		shop = 'normal',
	},
	{
		name = 'Lampadati Komoda',
		brand = 'Lampadati',
		model = 'Komoda',
		price = 42000,
		category = 'sports',
        categoryLabel = 'Sports',
		hashname = 'komoda',
		hash = `komoda`,
		shop = 'normal',
	},
	{
		name = 'Karin Kuruma',
		brand = 'Karin',
		model = 'Kuruma',
		price = 42000,
		category = 'sports',
        categoryLabel = 'Sports',
		hashname = 'kuruma',
		hash = `kuruma`,
		shop = 'normal',
	},
	{
		name = 'Obey Ninef',
		brand = 'Obey',
		model = 'Ninef',
		price = 85600,
		category = 'sports',
        categoryLabel = 'Sports',
		hashname = 'ninef',
		hash = `ninef`,
		shop = 'normal',
	},
	{
		name = 'Maibatsu Penumbra FF',
		brand = 'Maibatsu',
		model = 'Penumbra FF',
		price = 85600,
		category = 'sports',
        categoryLabel = 'Sports',
		hashname = 'penumbra',
		hash = `penumbra`,
		shop = 'normal',
	},
	{
		name = 'Benefactor Schlagen GT',
		brand = 'Benefactor',
		model = 'Schlagen GT',
		price = 84150,
		category = 'sports',
        categoryLabel = 'Sports',
		hashname = 'schlagen',
		hash = `schlagen`,
		shop = 'normal',
	},
	{
		name = 'Dinka Sugoi',
		brand = 'Dinka',
		model = 'Sugoi',
		price = 84150,
		category = 'sports',
        categoryLabel = 'Sports',
		hashname = 'sugoi',
		hash = `sugoi`,
		shop = 'normal',
	},
	{
		name = 'Karin Futo GTX',
		brand = 'Karin',
		model = 'Futo GTX',
		price = 84150,
		category = 'sports',
        categoryLabel = 'Sports',
		hashname = 'futo2',
		hash = `futo2`,
		shop = 'normal',
	},
	{
		name = 'Annis Elegy ',
		brand = 'Annis',
		model = 'Elegy',
		price = 42000,
		category = 'sports',
        categoryLabel = 'Sports',
		hashname = 'elegy',
		hash = `elegy`,
		shop = 'normal',
	},
	{
		name = 'Karin Sultan RS',
		brand = 'Karin',
		model = 'Sultan RS',
		price = 37000,
		category = 'sports',
        categoryLabel = 'Sports',
		hashname = 'sultanrs',
		hash = `sultanrs`,
		shop = 'normal',
	},
	{
		name = 'Karin Sultan',
		brand = 'Karin',
		model = 'Sultan',
		price = 35000,
		category = 'sports',
        categoryLabel = 'Sports',
		hashname = 'sultan2',
		hash = `sultan2`,
		shop = 'normal',
	},
	{
		name = 'Karin Calico GTF',
		brand = 'Karin',
		model = 'Calico GTF',
		price = 32000,
		category = 'sports',
        categoryLabel = 'Sports',
		hashname = 'calico',
		hash = `calico`,
		shop = 'normal',
	},
	{
		name = 'Annis ZR 350',
		brand = 'Annis',
		model = 'ZR 350',
		price = 87030,
		category = 'sports',
        categoryLabel = 'Sports',
		hashname = 'zr350',
		hash = `zr350`,
		shop = 'normal',
	},
	{
		name = 'Lampadati Michelli GT',
		brand = 'Lampadati',
		model = 'Michelli GT',
		price = 87030,
		category = 'sportsclassics',
        categoryLabel = 'Sports Classics',
		hashname = 'michelli',
		hash = `michelli`,
		shop = 'normal',
	},
	{
		name = 'Vapid Retinue',
		brand = 'Vapid',
		model = 'Retinue',
		price = 87030,
		category = 'sportsclassics',
        categoryLabel = 'Sports Classics',
		hashname = 'retinue',
		hash = `retinue`,
		shop = 'normal',
	},
	{
		name = 'Annis Savestra',
		brand = 'Annis',
		model = 'Savestra',
		price = 87030,
		category = 'sportsclassics',
        categoryLabel = 'Sports Classics',
		hashname = 'savestra',
		hash = `savestra`,
		shop = 'normal',
	},
	{
		name = 'Übermacht Zion',
		brand = 'Übermacht',
		model = 'Zion',
		price = 87030,
		category = 'sportsclassics',
        categoryLabel = 'Sports Classics',
		hashname = 'zion3',
		hash = `zion3`,
		shop = 'normal',
	},
	{
		name = 'Progen Emerus',
		brand = 'Progen',
		model = 'Emerus',
		price = 50000,
		category = 'super',
		categoryLabel = 'Supercar',
		hashname = 'emerus',
		hash = `emerus`,
		shop = 'normal',
	},
	{
		name = 'Overflod Entity XXR',
		brand = 'Overflod',
		model = 'Entity XXR',
		price = 50000,
		category = 'super',
		categoryLabel = 'Supercar',
		hashname = 'entity2',
		hash = `entity2`,
		shop = 'normal',
	},
	{
		name = 'Pegassi Tempesta',
		brand = 'Pegassi',
		model = 'Tempesta',
		price = 50000,
		category = 'super',
		categoryLabel = 'Supercar',
		hashname = 'tempesta',
		hash = `tempesta`,
		shop = 'normal',
	},
	{
		name = 'Pegassi Zentorno',
		brand = 'Pegassi',
		model = 'Zentorno',
		price = 50000,
		category = 'super',
		categoryLabel = 'Supercar',
		hashname = 'zentorno',
		hash = `zentorno`,
		shop = 'normal',
	},
	{
		name = 'Overflod Tyrant',
		brand = 'Overflod',
		model = 'Tyrant',
		price = 50000,
		category = 'super',
		categoryLabel = 'Supercar',
		hashname = 'tyrant',
		hash = `tyrant`,
		shop = 'normal',
	},
	{
		name = 'Grotti Visione',
		brand = 'Grotti',
		model = 'Visione',
		price = 50000,
		category = 'super',
		categoryLabel = 'Supercar',
		hashname = 'visione',
		hash = `visione`,
		shop = 'normal',
	},
	{
		name = 'Ghotti Turismo R',
		brand = 'Ghotti',
		model = 'Turismo R',
		price = 185000,
		category = 'super',
		categoryLabel = 'Supercar',
		hashname = 'turismor',
		hash = `turismor`,
		shop = 'normal',
    },
}